### ISSUE TITLE
Crash on import.

### ISSUE THREAD

**Issue by cuspucefyo** [0xpr03/VocableTrainer-Android#8]
I just click on import and get...

```
W/dalvikvm( 3531): threadid=1: thread exiting with uncaught exception (group=0x41f25ce0)
W/dalvikvm( 3531): threadid=1: uncaught exception occurred
W/System.err( 3531): java.lang.NullPointerException
W/System.err( 3531):    at vocabletrainer.heinecke.aron.vocabletrainer.Activities.lib.EntryListAdapter.getView(EntryListAdapter.java:95)
W/System.err( 3531):    at android.widget.AbsListView.obtainView(AbsListView.java:2338)
W/System.err( 3531):    at android.widget.ListView.makeAndAddView(ListView.java:1812)
W/System.err( 3531):    at android.widget.ListView.fillDown(ListView.java:698)
W/System.err( 3531):    at android.widget.ListView.fillFromTop(ListView.java:759)
W/System.err( 3531):    at android.widget.ListView.layoutChildren(ListView.java:1645)
W/System.err( 3531):    at android.widget.AbsListView.onLayout(AbsListView.java:2149)
W/System.err( 3531):    at android.view.View.layout(View.java:15140)
W/System.err( 3531):    at android.view.ViewGroup.layout(ViewGroup.java:4866)
W/System.err( 3531):    at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1197)
W/System.err( 3531):    at android.view.View.layout(View.java:15140)
W/System.err( 3531):    at android.view.ViewGroup.layout(ViewGroup.java:4866)
W/System.err( 3531):    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
W/System.err( 3531):    at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
W/System.err( 3531):    at android.view.View.layout(View.java:15140)
W/System.err( 3531):    at android.view.ViewGroup.layout(ViewGroup.java:4866)
W/System.err( 3531):    at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
W/System.err( 3531):    at android.view.View.layout(View.java:15140)
W/System.err( 3531):    at android.view.ViewGroup.layout(ViewGroup.java:4866)
W/System.err( 3531):    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
W/System.err( 3531):    at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
W/System.err( 3531):    at android.view.View.layout(View.java:15140)
W/System.err( 3531):    at android.view.ViewGroup.layout(ViewGroup.java:4866)
W/System.err( 3531):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
W/System.err( 3531):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
W/System.err( 3531):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
W/System.err( 3531):    at android.view.View.layout(View.java:15140)
W/System.err( 3531):    at android.view.ViewGroup.layout(ViewGroup.java:4866)
W/System.err( 3531):    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
W/System.err( 3531):    at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
W/System.err( 3531):    at android.view.View.layout(View.java:15140)
W/System.err( 3531):    at android.view.ViewGroup.layout(ViewGroup.java:4866)
W/System.err( 3531):    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2342)
W/System.err( 3531):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2048)
W/System.err( 3531):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1211)
W/System.err( 3531):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6282)
W/System.err( 3531):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
W/System.err( 3531):    at android.view.Choreographer.doCallbacks(Choreographer.java:591)
W/System.err( 3531):    at android.view.Choreographer.doFrame(Choreographer.java:560)
W/System.err( 3531):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
W/System.err( 3531):    at android.os.Handler.handleCallback(Handler.java:808)
W/System.err( 3531):    at android.os.Handler.dispatchMessage(Handler.java:103)
W/System.err( 3531):    at android.os.Looper.loop(Looper.java:193)
W/System.err( 3531):    at android.app.ActivityThread.main(ActivityThread.java:5323)
W/System.err( 3531):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 3531):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 3531):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
W/System.err( 3531):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
W/System.err( 3531):    at dalvik.system.NativeStart.main(Native Method)
W/dalvikvm( 3531): threadid=1: calling UncaughtExceptionHandler
E/AndroidRuntime( 3531): FATAL EXCEPTION: main
E/AndroidRuntime( 3531): Process: vocabletrainer.heinecke.aron.vocabletrainer, PID: 3531
E/AndroidRuntime( 3531): java.lang.NullPointerException
E/AndroidRuntime( 3531):        at vocabletrainer.heinecke.aron.vocabletrainer.Activities.lib.EntryListAdapter.getView(EntryListAdapter.java:95)
E/AndroidRuntime( 3531):        at android.widget.AbsListView.obtainView(AbsListView.java:2338)
E/AndroidRuntime( 3531):        at android.widget.ListView.makeAndAddView(ListView.java:1812)
E/AndroidRuntime( 3531):        at android.widget.ListView.fillDown(ListView.java:698)
E/AndroidRuntime( 3531):        at android.widget.ListView.fillFromTop(ListView.java:759)
E/AndroidRuntime( 3531):        at android.widget.ListView.layoutChildren(ListView.java:1645)
E/AndroidRuntime( 3531):        at android.widget.AbsListView.onLayout(AbsListView.java:2149)
E/AndroidRuntime( 3531):        at android.view.View.layout(View.java:15140)
E/AndroidRuntime( 3531):        at android.view.ViewGroup.layout(ViewGroup.java:4866)
E/AndroidRuntime( 3531):        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1197)
E/AndroidRuntime( 3531):        at android.view.View.layout(View.java:15140)
E/AndroidRuntime( 3531):        at android.view.ViewGroup.layout(ViewGroup.java:4866)
E/AndroidRuntime( 3531):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
E/AndroidRuntime( 3531):        at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
E/AndroidRuntime( 3531):        at android.view.View.layout(View.java:15140)
E/AndroidRuntime( 3531):        at android.view.ViewGroup.layout(ViewGroup.java:4866)
E/AndroidRuntime( 3531):        at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
E/AndroidRuntime( 3531):        at android.view.View.layout(View.java:15140)
E/AndroidRuntime( 3531):        at android.view.ViewGroup.layout(ViewGroup.java:4866)
E/AndroidRuntime( 3531):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
E/AndroidRuntime( 3531):        at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
E/AndroidRuntime( 3531):        at android.view.View.layout(View.java:15140)
E/AndroidRuntime( 3531):        at android.view.ViewGroup.layout(ViewGroup.java:4866)
E/AndroidRuntime( 3531):        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
E/AndroidRuntime( 3531):        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
E/AndroidRuntime( 3531):        at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
E/AndroidRuntime( 3531):        at android.view.View.layout(View.java:15140)
E/AndroidRuntime( 3531):        at android.view.ViewGroup.layout(ViewGroup.java:4866)
E/AndroidRuntime( 3531):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
E/AndroidRuntime( 3531):        at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
E/AndroidRuntime( 3531):        at android.view.View.layout(View.java:15140)
E/AndroidRuntime( 3531):        at android.view.ViewGroup.layout(ViewGroup.java:4866)
E/AndroidRuntime( 3531):        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2342)
E/AndroidRuntime( 3531):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2048)
E/AndroidRuntime( 3531):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1211)
E/AndroidRuntime( 3531):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6282)
E/AndroidRuntime( 3531):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
E/AndroidRuntime( 3531):        at android.view.Choreographer.doCallbacks(Choreographer.java:591)
E/AndroidRuntime( 3531):        at android.view.Choreographer.doFrame(Choreographer.java:560)
E/AndroidRuntime( 3531):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
E/AndroidRuntime( 3531):        at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime( 3531):        at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime( 3531):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 3531):        at android.app.ActivityThread.main(ActivityThread.java:5323)
E/AndroidRuntime( 3531):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3531):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3531):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
E/AndroidRuntime( 3531):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
E/AndroidRuntime( 3531):        at dalvik.system.NativeStart.main(Native Method)
V/Provider/Settings(  626): get setting for user 0 by user 0 so skipping cache


```

Same I got after click on "Create list".

**Comment by 0xpr03** [comment]
I just discovered that failure too yesterday. e5e594a should fix the problem.
Can you please try out 0.3.2 ?

Fun fact: I fixed this before I saw your report.

**Comment by 0xpr03** [comment]
@cuspucefyo 0.3.2 [has landet](https://f-droid.org/wiki/page/vocabletrainer.heinecke.aron.vocabletrainer) on f-droid, could you please test it out and report if that fixes the problem ?

**Comment by 0xpr03** [comment]
I'm closing this as I haven't heard anything lately, also I'm sure to have reproduced & closed this issue regarding Android KitKat.
